/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "wheel_motor_messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(WheelMotorCommand, WheelMotorCommand, AUTO)


PB_BIND(WheelMotorState, WheelMotorState, AUTO)





